### ISSUE TITLE
ngx_log_debug设计不合理？

### ISSUE THREAD

**Issue by lotluck** [lotluck/nginx-1.16.0#6]
### 自己编写的代码引用nginx源文件的时候core掉，突然发现是ngx_log_debug3问题，core栈如下
```
(gdb) bt
  #0  ngx_memalign (alignment=alignment@entry=16, size=size@entry=1024, log=log@entry=0x0) at src/os/unix/ngx_alloc.c:84
  #1  0x0000000000400a61 in ngx_create_pool (size=1024, log=0x0) at src/core/ngx_palloc.c:23
  #2  0x0000000000403405 in main () at myngx_pool.c:58
  (gdb) f 0
  #0  ngx_memalign (alignment=alignment@entry=16, size=size@entry=1024, log=log@entry=0x0) at src/os/unix/ngx_alloc.c:84
        84          ngx_log_debug3(NGX_LOG_DEBUG_ALLOC, log, 0,
  (gdb)
```
### 分析 & 问题原因 log为空的时候就直接core掉
```
#define ngx_log_debug(level, log, args...)                                    \
    if ((log)->log_level & level)                                             \
        ngx_log_error_core(NGX_LOG_DEBUG, log, args)

```

**Comment by lotluck** [comment]
### 解决方案: 原来自己开启--with-debug功能，编译的时候关闭就好
